SELECT * FROM movies_booking.movie_booking_basic_csv;
SELECT * FROM movies_booking.movie_booking_basic_csv WHERE ReleaseDate BETWEEN '2024-01-01' AND '2024-12-31';
SELECT Title, Genre FROM movies_booking.movie_booking_basic_csv;
SELECT DISTINCT Genre FROM movies_booking.movie_booking_basic_csv;
SELECT * FROM movies_booking.customers WHERE City = 'Chennai';
SELECT * FROM movies_booking.bookings where SeatsBooked > 3;
SELECT * FROM movies_booking.payments where Status = 'Pending';
SELECT * FROM movies_booking.movie_booking_basic_csv WHERE ReleaseDate BETWEEN '01-01-2023' AND '01-01-2024';
SELECT * FROM movies_booking.shows WHERE TicketPrice BETWEEN 200 AND 400;
SELECT * FROM movies_booking.customers WHERE Name LIKE 'C%';
SELECT * FROM movies_booking.movie_booking_basic_csv ORDER BY ReleaseDate ASC;
SELECT * FROM movies_booking.bookings ORDER BY BookingDate DESC;
SELECT CustomerID, SUM(SeatsBooked) FROM movies_booking.bookings GROUP BY CustomerID;
SELECT PaymentID, SUM(Amount) AS Total_Amount_paid FROM movies_booking.payments GROUP BY PaymentID;
SELECT ShowID, COUNT(*) FROM movies_booking.bookings GROUP BY ShowID;
SELECT CustomerID, COUNT(*) TotalBookings FROM movies_booking.bookings GROUP BY CustomerID HAVING COUNT(*) > 2;
SELECT ShowID, SUM(SeatsBooked) FROM movies_booking.bookings GROUP BY ShowID HAVING SUM(SeatsBooked) > 10;
DELETE FROM movies_booking.bookings WHERE BookingID = 5 ;
DELETE FROM movies_booking.payments WHERE Status = 'Pending' AND PaymentDate < '2024-01-01';
SELECT * FROM movies_booking.customers order by CustomerID LIMIT 5;
SELECT * FROM movies_booking.customers ORDER BY CustomerID LIMIT 5 OFFSET 5;
SELECT DISTINCT CustomerID FROM movies_booking.bookings WHERE ShowID IN ( SELECT ShowID FROM movies_booking.shows WHERE TicketPrice > 400 );
SELECT DISTINCT MovieID FROM movies_booking.shows WHERE ShowID IN (SELECT ShowID FROM movies_booking.bookings GROUP BY ShowID HAVING COUNT(BookingID) > 10);
SELECT c.Name, b.BookingID, b.SeatsBooked, b.BookingDate FROM movies_booking.customers c INNER JOIN movies_booking.bookings b ON c.CustomerID = b.CustomerID;
SELECT s.ShowID, s.ShowDate, s.TicketPrice, m.Title FROM movies_booking.shows s LEFT JOIN movies_booking.movie_booking_basic_csv m ON s.MovieID = m.MovieID;
SELECT b.BookingID, b.CustomerID, p.PaymentID, p.Amount, p.Status FROM movies_booking.bookings b RIGHT JOIN movies_booking.payments p ON b.BookingID = p.BookingID;
SELECT s.ShowID, m.Title AS MovieTitle, t.Name , s.ShowDate FROM movies_booking.shows s INNER JOIN movies_booking.movie_booking_basic_csv m ON s.MovieID = m.MovieID INNER JOIN movies_booking.theatres t ON s.TheatreID = t.TheatreID;
SELECT CustomerID, BookingDate, COUNT(DISTINCT ShowID)  FROM movies_booking.bookings GROUP BY CustomerID, BookingDate HAVING COUNT(DISTINCT ShowID) > 1;